# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='FileServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('webui', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.FileResource')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scraper_source', models.CharField(choices=[(b'imdb', b'ImDB'), (b'thetvdb', b'The TV DB')], max_length=255)),
                ('scraper_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scrapers', models.ManyToManyField(blank=True, to='mediamanager.Scraper')),
            ],
        ),
        migrations.CreateModel(
            name='ShowEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.Show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.Show')),
            ],
        ),
        migrations.CreateModel(
            name='StorageDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.FileServer')),
            ],
        ),
        migrations.CreateModel(
            name='StorageFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains', models.CharField(choices=[(b'movies', b'Movies'), (b'shows', b'Shows')], max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.StorageDisk')),
            ],
        ),
        migrations.AddField(
            model_name='showstorage',
            name='storagefolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.StorageFolder'),
        ),
        migrations.AddField(
            model_name='showepisode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.ShowSeason'),
        ),
        migrations.AddField(
            model_name='movie',
            name='scrapers',
            field=models.ManyToManyField(blank=True, to='mediamanager.Scraper'),
        ),
        migrations.AddField(
            model_name='episoderesource',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.ShowEpisode'),
        ),
        migrations.AddField(
            model_name='episoderesource',
            name='file_res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.FileResource'),
        ),
    ]
