# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='file_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
