# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0003_showepisode_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showepisode',
            options={'ordering': ('season__nr', 'nr')},
        ),
    ]
