# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0004_auto_20180823_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='md_duration',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='md_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
