# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0005_auto_20180823_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='md_channel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='md_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='md_summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='md_video_height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='md_video_width',
            field=models.IntegerField(default=-1),
        ),
    ]
