# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0008_auto_20180824_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showepisode',
            options={'ordering': ('season__show', 'season__nr', 'nr')},
        ),
        migrations.AddField(
            model_name='fileresource',
            name='show_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediamanager.ShowStorage'),
        ),
    ]
