# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-24 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0009_auto_20180824_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='md_summary_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
