# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0010_fileresource_md_summary_raw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileserver',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='scraper',
            options={'ordering': ('name', 'scraper_source')},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('name', 'language')},
        ),
        migrations.AlterModelOptions(
            name='showseason',
            options={'ordering': ('show', 'nr')},
        ),
        migrations.AlterModelOptions(
            name='showstorage',
            options={'ordering': ('show', 'storagefolder')},
        ),
        migrations.AlterModelOptions(
            name='storagedisk',
            options={'ordering': ('server', 'name')},
        ),
        migrations.AlterModelOptions(
            name='storagefolder',
            options={'ordering': ('disk', 'contains')},
        ),
    ]
