# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0013_auto_20180825_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDiskOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('op_type', models.CharField(choices=[(b'cp', b'Copy'), (b'rm', b'Remove')], max_length=255)),
                ('file_size', models.BigIntegerField(default=-1)),
                ('took_seconds', models.BigIntegerField(default=-1)),
                ('speed', models.BigIntegerField(default=-1)),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.StorageDisk')),
            ],
        ),
        migrations.AlterModelOptions(
            name='episoderesource',
            options={'ordering': ('episode', '-file_res__file_size')},
        ),
    ]
