# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0014_auto_20180825_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='file_path',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='storagediskoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
