# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0015_auto_20180825_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scraper',
            options={'ordering': ('name', 'scraper_priority', 'scraper_source')},
        ),
        migrations.AddField(
            model_name='episoderesource',
            name='match_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='episoderesource',
            name='match_similarity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='scraper',
            name='scraper_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scraper',
            name='scraper_url',
            field=models.CharField(blank=True, help_text=b'With tailing /', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='auto_assign_multiep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='auto_assign_multiep_sep',
            field=models.CharField(default=' / ', max_length=100),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='scraper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='scraper_source',
            field=models.CharField(choices=[(b'imdb', b'ImDB'), (b'thetvdb', b'The TV DB'), (b'fernsehserien.de', b'fernsehserien.de')], max_length=255),
        ),
    ]
