# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0017_auto_20180829_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='orig_language',
            field=models.CharField(choices=[(b'de', b'Deutsch (de)'), (b'en', b'English (en)')], default=b'en', max_length=3),
        ),
    ]
