# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-24 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0018_scraper_orig_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='episoderesource',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
