# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0020_fileresource_file_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
